name: Check banned imports
on:
  - pull_request
  - push
  - workflow_dispatch
permissions: {}
jobs:
  check-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Check imports
        run: .github/workflows/ban-imports.sh
