name: Pre-Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    env:
      GIT_URL: ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.sha }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Set up gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew clean test includeBackupRepo remapJar --no-daemon
        env:
          NEU_RELEASE: true
      - uses: actions/upload-artifact@v3
        with:
          path: build/libs/*.jar
      - run: ./.github/workflows/upload-release.sh
        env:
          GH_TOKEN: ${{ github.token }}
